### ISSUE TITLE
Unable to Adopt new devices

### ISSUE THREAD

**Issue by tda2806** [jkunczik/home-assistant-omada#88]
I have just purchased a new SG2210P switch, which I cannot adopt, the adoption fails because the device fails to respond. I have successfully adopted devices to this site in the past (including a SG2210). A port scan of my Home Assistant host shows that ports  29811 to 29816 are open but 29810 is closed, is this normal?

**Comment by vh13294** [comment]
New access points also cannot be adopted

Here is part of the error messsage
`
: timeout wait adopt watch result of OmadacId(_) DeviceMac(_+s=) BusinessId(topic=smb_omada_business_, id=b1f0b2e7-be41-4db6-94d1-f696db6f8827), 
response:OperationResponse(errorCode=-39002, msg=Device adoption failed because the device does not respond to adopt commands., 
result=AdoptOneDeviceStatusResultVO(mac=AC-15-A2-E1-F9-A8, status=24, statusCategory=2, specificationNote=null), auditLogReturn=null, auditLogReturnList=null)

05-07-2025 21:26:30.615 INFO [https-jsse-nio-8043-exec-5] [] c.t.s.o.m.t.d.a.a(): Failed to find lldpPortMap for gateway <69-3E-E0>, omadacId=
`

**Comment by Pseudophryne** [comment]
I've been experiencing this issue since moving to 5.15.x to get by this issue I added a SG2016P & EAP620 by configuring the controller address in the web portal of each device, this then prompted me for username and password when adopting.  Not a fix but this work around might help you.  I believe (but cannot test my theory) it is to do with the changes in Omada with 5.15 and the older code level on the switch/AP.

**Comment by tda2806** [comment]
> I've been experiencing this issue since moving to 5.15.x to get by this issue I added a SG2016P & EAP620 by configuring the controller address in the web portal of each device, this then prompted me for username and password when adopting. Not a fix but this work around might help you. I believe (but cannot test my theory) it is to do with the changes in Omada with 5.15 and the older code level on the switch/AP.

Thank you! The setting can be found at System->Controller Settings-> Controller Inform URL

**Comment by Pseudophryne** [comment]
After a bit of reading today I think we may be missing some ports in the Docker Container - I'll investigate the next few days and see if I can test.

Docker file has "EXPOSE 8088 8043 8843 29810/udp 29811 29812 29813 29814"

Docker file may need to have 29815, 29816 added.

**Comment by tda2806** [comment]
1. 

> After a bit of reading today I think we may be missing some ports in the Docker Container - I'll investigate the next few days and see if I can test.
> 
> Docker file has "EXPOSE 8088 8043 8843 29810/udp 29811 29812 29813 29814"
> 
> Docker file may need to have 29815, 29816 added.

I am not sure the issue lies with just this implementation. When trying to isolate the issue I did try to use the Windows version of the Omada controller and that failed to adopt the device as well.

https://www.tp-link.com/uk/support/faq/3281/ details ports and their use. Port 27001/udp is mentioned there.

**Comment by Jeruntu** [comment]
Looks like it is related to this issue: https://github.com/mbentley/docker-omada-controller/issues/573

This has been solved in mbentley: https://github.com/mbentley/docker-omada-controller/pull/574
I'll update the submodule later today.

**Comment by mbentley** [comment]
The adoption failures remind me of when they added a port required for adoption but I see nothing in their documentation about new ports.  The controller does seem to be listening on another port from a netstat but apparently exposing that doesn’t help.

**Comment by tda2806** [comment]
I am unconvinced that this is a port issue on the docker. During my troubleshooting of the problem I installed the Windows version on the manager and tried and failed to adopt the switch. This may be an issue with  V5.15, I have an open ticket with Tp-link, I will advise if I (ever) get a response.

**Comment by mbentley** [comment]
Great data point @tda2806!  I've always gotten push back from support any time I've reported an issue where they need me to prove it's not a containerization problem, which I understand, but the blame seems to get shifted to that regularly.  At least recently, I've had some slow responses from support.  I put in a ticket April 4th, finally got a response May 1st asking if I was still experiencing the problem and still waiting on further response from them after that.  The other place that I've gone for support is the [TP-Link community forums](https://community.tp-link.com/en/business/forum/582) as I seem  to get reasonably quick responses there.

**Comment by Pseudophryne** [comment]
@mbentley I fired up a test v5.15.20.20 controller I have and the controller mentions _UDP 19810_, UDP 29810, TCP 29811, TCP 29812, TCP 29813, TCP 29814, TCP 29815, and TCP 29816.

Omada documentation lists UDP 19810 as required to manage OLT devices only but maybe this is worth adding.

![Image](https://github.com/user-attachments/assets/0f696841-e14c-437c-8ef5-c42f45121bcb)

**Comment by mbentley** [comment]
Thanks - I just added that via https://github.com/mbentley/docker-omada-controller/pull/575

**Comment by Pseudophryne** [comment]
Ditto on the ports in the Home Assistant container except 80 & 443 which are not used in Omada Software Controller allegedly 🙂 
````
netstat -ltnpu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:42677        0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:27217         0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::29811                :::*                    LISTEN      -                   
tcp6       0      0 :::29815                :::*                    LISTEN      -                   
tcp6       0      0 :::29814                :::*                    LISTEN      -                   
tcp6       0      0 :::29813                :::*                    LISTEN      -                   
tcp6       0      0 :::29812                :::*                    LISTEN      -                   
tcp6       0      0 :::29816                :::*                    LISTEN      -                   
tcp6       0      0 :::8043                 :::*                    LISTEN      -                   
tcp6       0      0 :::8088                 :::*                    LISTEN      -                   
tcp6       0      0 :::9098                 :::*                    LISTEN      -                   
tcp6       0      0 :::8843                 :::*                    LISTEN      -                   
udp        0      0 127.0.0.11:52574        0.0.0.0:*                           -                   
udp6       0      0 :::27001                :::*                                -                   
udp6       0      0 :::19810                :::*                                -                   
udp6       0      0 :::29810                :::*                                -

**Comment by tda2806** [comment]
I have a response from Omada Support!

"Please connect the SG2210P and PC directly to the router, ensuring there are no devices in between. Try the adoption process. If the adoption still fails, change the Ethernet cable and try again. 
 
You can also log into the management page of the switch in Standalone Mode and go to SYSTEM> Controller Settings. In Controller Inform URL, specify Inform URL/IP Address as the controller’s IP address."

From the second paragraph above it would seem that this is a known issue and currently the adoption process needs this additional step for the time being.

Perhaps it would be good to add this workaround to the readme?

**Comment by tda2806** [comment]
I asked Omada support this: 
"The workaround identified in the 2nd paragraph worked. Can you please tell me when this will be fixed so that the adoption process doesn't require this, undocumented, additional step?"
They responded thus:
"Typically, normal adoption of devices does not require this step. The failure to adopt this time may be due to delays in command issuance or the controller not recognizing the correct address. Please feel free to use the device normally afterward, and if you have any questions, don't hesitate to contact us."

I think the response can be filed under "Tell me you have a known issue, without telling me you have a known issue"

Can we agree to close this issue down once the readme has been amended?

**Comment by ducastelg** [comment]
Same problem for me with beta-5.15.24.14 running on a Home Assistant Green (EAP245(EU) v4.0 antenna).
Specifying the IP address of the Home Assistant Green in the standalone mode "SYSTEM > Controller Settings" worked perfectly.
Thank you all for solving my problem.
Leave this post visible for future users who have the same problem until tp-link resolves it.
I'd like to take this opportunity to thank the developers and contributors for this great integration...
Good work to all.

**Comment by LittleLama** [comment]
This issue seems to still be current in the stable version as this one has not been updated since April.
Any details about when this will be updated with all reachable ports ? I'm spending hours to make it work so I'm wondering does it worth it :D

**Comment by LittleLama** [comment]
The workaround, setting the controller IP in AP, didn't work for me. New controller see AP but can't adopt them 

Error message is : Device Adoption Failed Because the Device does not Respond to Adopt Commands. 

Didn't succeed to test if ports were well openened to let adoption succeed but I'm not an expert.

**Comment by LittleLama** [comment]
Non, j'ai un contrôleur qui fonctionne parfaitement sur un Docker hébergé sur une autre machine, qui est souvent éteinte.
Le contrôleur sur home assistant, bien que son administration soit accessible, ne semble pas visible sur le réseau.
Je n'ai rien pu y faire de plus

**Comment by matt0020190** [comment]
Work around works for me and I've needed to do it several times on different new devices.  It's a real ball ache though,  but life is full of small inconveniences. Just amazed TP-Link have not fixed this.... it's kind of a fundamental

**Comment by gambigo** [comment]
I'm curious, are you guys planning to change network_mode or I'm stuck with using fork ?
